[theme]
primaryColor = "#2065f8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1B2951"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
